server:
  port: 8090

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#endpoints:
#  health:
#    sensitive: false
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true